httpd:
  image: httpd
  hostname: apache2
  ports:
    - "80:80"
  environment:
  volumes:
    - /vagrant:/vagrant
  restart: always
monitor:
  image: ubuntu
  hostname: monitor
  links:
    - httpd:httpd
  volumes:
    - /vagrant:/vagrant
  environment:
    - HOSTNAMEMONITORING=webservernr2
    - PORTS=SSH:22;tomcat:8081;HTTP:80
    - DISPLAYNAME=WebServer Nr2
    - MONITORING_SERVER=monitoring
    - NSCAPASS=SDFasdfasdf3adf
    - HOSTINT=httpd
  restart: always